// <auto-generated />
using DanceCompetition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanceCompetition.Migrations
{
    [DbContext(typeof(DanceCompetitionContext))]
    [Migration("20221221011153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanceCompetition.Models.DancePair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("grade1")
                        .HasColumnType("int");

                    b.Property<int>("grade2")
                        .HasColumnType("int");

                    b.Property<int>("grade3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DancePair");
                });
#pragma warning restore 612, 618
        }
    }
}
